### ISSUE TITLE
Docker checklist for EasyEngine v4

### ISSUE THREAD

**Issue by rahul286** [EasyEngine/easyengine#945]
_Plese read this blog post for background/context - https://easyengine.io/blog/how-we-plan-to-use-docker-in-easyengine-v4/._

This is meta issue to track progress. Actual work is being done in - https://github.com/EasyEngine/docker-compose-wordpress/

**Notes**
Make sure all following tests are carried over DigitalOcean (or equivalent) $5 VPS (512MB RAM).
The site(s) must use public domain/subdomain and always be served on port 80.

**Issues to work on**
- [x] Running a single website using docker (compose) - https://github.com/EasyEngine/docker-compose-wordpress/issues/1
- [x] Running multiple websites using docker (compose) - https://github.com/EasyEngine/docker-compose-wordpress/issues/3
- [x] Running WordPress Multisite using docker (compose) - https://github.com/EasyEngine/docker-compose-wordpress/issues/4
- [x] Test SSL - https://github.com/EasyEngine/docker-compose-wordpress/issues/5
- [x] Test caching - https://github.com/EasyEngine/docker-compose-wordpress/issues/6
- [x] Config files - https://github.com/EasyEngine/docker-compose-wordpress/issues/7
- [x] Log files - https://github.com/EasyEngine/docker-compose-wordpress/issues/8
- [x] Common Service container approach? - https://github.com/EasyEngine/docker-compose-wordpress/issues/9
- [x] Postfix/email sending - https://github.com/EasyEngine/docker-compose-wordpress/issues/10
- [x] Linux cron (wp-cron disable) - https://github.com/EasyEngine/docker-compose-wordpress/issues/11
